### ISSUE TITLE
app.js:1 Uncaught TypeError: window.languages.forEach is not a function

### ISSUE THREAD

**Issue by dumithsalinda** [HansSchouten/Laravel-Pagebuilder#31]
Hi, First I must say this is a great project and thank you for creating it. 

And I'm using Laravel page builder v0.12.0 with laravel 7. And when i updated the package from v0.10.0 to current version i'm getting this error.. 

![image](https://user-images.githubusercontent.com/1443237/90469003-58598700-e135-11ea-89b3-9a14a01e835c.png)

**Comment by HansSchouten** [comment]
Hi, thanks! Can you check using your browser console whether window.languages is set and what value it has?

**Comment by dumithsalinda** [comment]
{en: "English"}
this is the value of window.languages

**Comment by HansSchouten** [comment]
Hmm that is indeed not an array, but an object. It might be the case that it only works with 2 languages enabled.

**Comment by dumithsalinda** [comment]
Thank you.
